### ISSUE TITLE
Remove requirement for explicit globals in translators

### ISSUE THREAD

**Issue by tjaffri** [tjaffri/msiot-samples#4]
We currently have declarations like this at the bottom of each translator. We need to discover these globals automatically so these declarations are not required.

// globals for JxCore host
global.initDevice = module.exports.initDevice;
global.getBeatsPerMinute = module.exports.getBeatsPerMinute;
global.getRRInterval = module.exports.getRRInterval;
global.getEnergyExpended = module.exports.getEnergyExpended;
global.getContactStatus = module.exports.getContactStatus;
global.disconnect = module.exports.disconnect;

**Comment by jasongin** [comment]
This is fixed by my PR https://github.com/tjaffri/msiot-samples/pull/2

**Comment by jasongin** [comment]
Merged as PR https://github.com/tjaffri/msiot-samples/pull/2
